version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: aseerkt
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finlabs
    ports:
      - '5430:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
